# Dependencies
# markdown: commonmark
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dorset Building Stone
tagline:          'A prototype website'
description:      'The building stones of Dorset from a geological perspective'
url:              https://geoffrowland.github.io/dbs/
baseurl:          "https://geoffrowland.github.io/dbs/"

author:
  name:           'The Dorset Building Stone Group'
  url:            https://twitter.com/mdo

paginate:         4

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/geoffrowland/hyde
