# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Dorset Building Stone
tagline:          'A prototype website'
description:      'The building stones of Dorset from a geological perspective'
url:              https://geoffrowland.github.io/hyde/
baseurl:          "https://geoffrowland.github.io/hyde/"

author:
  name:           'The Dorset Building Stone Group'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
